{
    'name': 'Custom Fields',
    'version': '18.0.1.0.0',
    'author': 'PPTS [India] Pvt.Ltd.',
    'website': 'https://www.pptssolutions.com',
    'category': 'Inventory/Stock',
    'sequence': 1,
    'summary': 'Product customization for Odoo 18',
    'description': """This module provides product customization features in Odoo 18.""",
    'depends': [
        'base_setup',
        'product',
        'stock',
        'base',
        'uom',
        'mrp',
        'account',
        'account_followup',
        'contacts',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/studio_custom_fields.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'application': True,
}
