{
    'name': 'Picking Excess Qty Restriction',
    'version': '18.0',
    'category': 'stock',
    'sequence':1,
    'author': 'PPTS [India] Pvt.Ltd.',
    'website': 'https://www.pptssolutions.com',
    'summary': 'This module does not allow users to validate excess quantity which is more than the demand',
    'description': """This module does not allow users to validate excess quantity which is more than the demand""",
    'depends': ['base','stock','sale'],
    'data': ['views/stock_picking.xml'],
    'installable': True,
    'auto-install': False,
    'license': 'LGPL-3',
    'application': True,
}
