import base64
from odoo import models, fields, api, _
from odoo.exceptions import UserError


class AuditMonthlyReport(models.Model):
    _name        = 'audit.monthly.report'
    _description = 'Monthly Stock Inventory Audit Report'
    _order       = 'report_date desc, id desc'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name         = fields.Char(string='Reference', readonly=True, index=True)
    report_date  = fields.Date(string='Report Date', readonly=True, index=True)
    report_month = fields.Char(string='Month', readonly=True)   # e.g. "May 2026"
    generated_by = fields.Many2one('res.users', string='Generated By',
                                   readonly=True, ondelete='set null')
    generated_on = fields.Datetime(string='Generated On', readonly=True)
    excel_file   = fields.Binary(string='Excel File', readonly=True, attachment=True)
    excel_filename = fields.Char(string='Filename', readonly=True)
    state        = fields.Selection([
        ('draft',  'Draft'),
        ('posted', 'Posted'),
    ], default='draft', readonly=True, string='Status')
    notes        = fields.Text(string='Notes')

    # ── Sequence ──────────────────────────────────────────────────────

    @api.model
    def _next_name(self):
        seq = self.env['ir.sequence'].next_by_code('audit.monthly.report')
        return seq or '/'

    # ── Smart creation ────────────────────────────────────────────────

    @api.model
    def create_from_data(self, excel_bytes, notes=None):
        """Create an audit record from raw Excel bytes. Called by wizard & cron."""
        today = fields.Date.today()
        month_label = today.strftime('%B %Y')

        # Prevent duplicate for same month (allow re-generation)
        existing = self.search([('report_month', '=', month_label)], limit=1)
        vals = {
            'report_date':    today,
            'report_month':   month_label,
            'generated_by':   self.env.uid,
            'generated_on':   fields.Datetime.now(),
            'excel_file':     base64.b64encode(excel_bytes),
            'excel_filename': f"stock_report_{today.strftime('%Y%m')}.xlsx",
            'state':          'posted',
            'notes':          notes,
        }
        if existing:
            vals['name'] = existing.name   # keep same reference on regeneration
            existing.write(vals)
            return existing
        else:
            vals['name'] = self._next_name()
            return self.create(vals)

    # ── Manual regenerate button ──────────────────────────────────────

    def action_regenerate(self):
        self.ensure_one()
        from ..wizard.audit_stock_report_wizard import build_workbook
        data, count = build_workbook(self.env)
        if not count:
            raise UserError(_('No stock data found. Cannot regenerate report.'))
        today = fields.Date.today()
        self.write({
            'excel_file':     base64.b64encode(data),
            'excel_filename': f"stock_report_{today.strftime('%Y%m')}.xlsx",
            'generated_by':   self.env.uid,
            'generated_on':   fields.Datetime.now(),
            'state':          'posted',
        })
        return {
            'type':   'ir.actions.client',
            'tag':    'display_notification',
            'params': {
                'title':   _('Report Regenerated'),
                'message': _('The monthly stock report has been updated.'),
                'type':    'success',
            },
        }

    def action_download(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_url',
            'url':  f'/web/content/audit.monthly.report/{self.id}/excel_file/'
                    f'{self.excel_filename}?download=true',
            'target': 'self',
        }

    @api.model
    def cron_generate_monthly_report(self):
        """Runs daily. Generates the report only on the last day of each month."""
        import calendar
        from datetime import date
        today = date.today()
        last_day = calendar.monthrange(today.year, today.month)[1]

        if today.day != last_day:
            # Not month-end — skip silently
            return
        
        from ..wizard.audit_stock_report_wizard import build_workbook
        try:
            data, count = build_workbook(self.env)
            if count:
                self.create_from_data(data, notes='Auto-generated by scheduled action')
        except Exception as e:
            # Log but don't crash the cron runner
            self.env['ir.logging'].create({
                'name':    'audit.monthly.report',
                'type':    'server',
                'level':   'ERROR',
                'message': f'Monthly stock report cron failed: {e}',
                'path':    'audit_monthly_report',
                'func':    'cron_generate_monthly_report',
                'line':    '0',
            })
